### PR TITLE
FUSETOOLS2-382 - when opening another editor while DDL editor is dirt…

### PR DESCRIPTION
**Pull request by lhein**
…y, changes will no longer be lost

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
Its hard to write a test for that. The former behavior was that the temporary file was deleted once another editor was opened. Given that the new temporary file is not even visible in the UI it would be rather hard to create a check for that without exposing more of the logic. Maybe @apupier has some idea?

**Comment by lhein** [comment]
In terms of UI testing I could imagine a test where a user Edits the schema, does some changes and then opens the yaml file. Then check the label of the DDL editor tab if there is a (deleted) marker or not.

**Comment by bfitzpat** [comment]
> Its hard to write a test for that.

Totally understand. Just wanted to raise it as a concern. I suspect that this is something that could bite a user if it suddenly goes awry.

**Comment by lhein** [comment]
@djelinek this pretty much includes https://issues.redhat.com/browse/FUSETOOLS2-334 too.

**Comment by lhein** [comment]
>     * it doesn't fully solve the addition of 2 ddl file at the same time, see https://issues.redhat.com/browse/FUSETOOLS2-334?focusedCommentId=14063020&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14063020

It doesn't need to. You describe the default behavior of VS Code. You can do the same with any other file in your project and it will always close the unmodified one to just have one editor opened at a time if possible.

**Comment by apupier** [comment]
> > ```
> > * it doesn't fully solve the addition of 2 ddl file at the same time, see https://issues.redhat.com/browse/FUSETOOLS2-334?focusedCommentId=14063020&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14063020
> > ```
> 
> 
> It doesn't need to. You describe the default behavior of VS Code. You can do the same with any other file in your project and it will always close the unmodified one to just have one editor opened at a time if possible.

this is not the default behavior that I have for other files

severalUnmodifiedFileOpened

**Comment by lhein** [comment]
Then your VS Code behaves different than mine. I posted a gif on the issue too.

**Comment by lhein** [comment]
>     * detected that when closing/reopening the ddl editors are unsynced https://issues.redhat.com/browse/FUSETOOLS2-393

Its not when closing / reopening the DDL editors but when restarting VSCode while the editor is open.

**Comment by apupier** [comment]
> > ```
> > * detected that when closing/reopening the ddl editors are unsynced https://issues.redhat.com/browse/FUSETOOLS2-393
> > ```
> 
> 
> Its not when closing / reopening the DDL editors but when restarting VSCode while the editor is open.

damn, I should have put punctuation (and be more precise):
"detected that when closing/reopening [the VS Code instance], the ddl editors are unsynced"

hopefully you were able to understand me (and correct me)

**Comment by lhein** [comment]
>     * naming of editor is a bit long now, not very convenient (but I think it can be improved when implementing one of the 2 next issues so not reporting a specific issue )

fixed in latest commit

**Comment by lhein** [comment]
So if I recap all the comments here there are a few issues left:
- it doesn't fully solve the addition of 2 ddl file at the same time, see https://issues.redhat.com/browse/FUSETOOLS2-334?focusedCommentId=14063020&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14063020
- detected that when closing/reopening VS Code then the ddl editors are no longer connected to the yaml file hence changes are not persistet to the YAML https://issues.redhat.com/browse/FUSETOOLS2-393
- Aurelien dislikes the way the commands are tested atm (https://issues.redhat.com/browse/FUSETOOLS2-410)

As everything got its own Jira I think this one could be merged then. Opposing voices?

**Pull request merged**
