### PR TITLE
FUSETOOLS2-332 - added check for empty name, fixed broken check for e…

### PR DESCRIPTION
**Pull request by lhein**
…nv var value to be undefined

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
Interestingly there are already a few tests already checking for undefined name and also for empty value. I am still a bit puzzled why those passed before.

**Comment by apupier** [comment]
> Interestingly there are already a few tests checking for undefined name and also for empty value. I am still a bit puzzled why those passed before.

the part of the code that you modified in this PR is not covered by tests.

In the tests you are not going through the "UI flow", only testing the end method, but the end method was not called for these cases.

To test it, you need to mock the callsl to `vscode.window.showInputBox`. it will allow to be closer to real usage.

**Comment by lhein** [comment]
that can be done in the UI tests. I will concentrate on unit testing.

**Comment by apupier** [comment]
> I will concentrate on unit testing.

technically, using mock and testing at the same file level, it remains unit testing.

I really think that it will be better to test with mocking the inputbox as compared to UI tests:
- faster feedback loop
- included in Code Coverage (even if it is because we are not able to include code coverage for UI tests)
- not depend on UI tests implementation for first release (or to release with untested code which is prone of bugs)

i'm not blocking the merge anyway. I just hope I won't have to develop on this part of code myself.

**Comment by lhein** [comment]
> I just hope I won't have to develop on this part of code myself.

You should really think about the way you comment on PRs Aurelien. This particular comment can be translated to something like "Your code is crap and I really hope I never have to touch it." and at the same time you write that you won't block the merge and set the approval.

**Comment by apupier** [comment]
> > I just hope I won't have to develop on this part of code myself.
> 
> You should really think about the way you comment on PRs Aurelien. This particular comment can be translated to something like "Your code is crap and I really hope I never have to touch it." and at the same time you write that you won't block the merge and set the approval.

I meant I hope I won't have to touch this code as there is no tests preventing me to introduce regressions

**Comment by lhein** [comment]
There are 90+ tests for this extension. I see that you are not happy with the way I test the commands. Message received.

**Comment by lhein** [comment]
> EDIT2: the environment variables for ConfigMap and secret and wrongly created with two imbricated "valueFrom"

interesting. investigating on that one.

**Comment by djelinek** [comment]
> that can be done in the UI tests. I will concentrate on unit testing.

Do we have already a JIRA for needed UI tests?

**Comment by lhein** [comment]
I will soon create a jira for that, Dominik. There are some issues upcoming which again change the behavior of datasources and environment variables. So I'd say its not yet worth tackling those.

**Pull request merged**
