### PR TITLE
FUSETOOLS2-405 - when creating a datasource preset all property value…

### PR DESCRIPTION
**Pull request by lhein**
…s with an empty string

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
When creating a datasource via the UI, we currently fill a set of predefined datasource properties into that datasource. Those properties have no pre-defined value. Due to the way the YAML library works it then only inserts the names of the properties to the YAML file but no the value tag. In our last dv tooling call @rareddy asked me to provide some dummy value for those datasource properties so the value tags are filled to the yaml. We decided to use the string `<empty>`. Now a user can open the YAML file directly and enter the values inside the YAML file without the need to first add the value tag. I know there is also the option to edit those values through the UI but that way we make it also more user friendly for people who prefer the direct editing of the YAML file. 

Just to restate: This only applies to datasource properties. Environment variables are not handled that way.

**Comment by apupier** [comment]
if I understand well YAML specification, you can have the node visible for null values. You need to provide `null` or `~` for an unsetted value.

see https://yaml.org/spec/1.2/spec.html#id2786563 (or https://symfony.com/doc/current/components/yaml/yaml_format.html#nulls which is clearer)

> Just to restate: This only applies to datasource properties. Environment variables are not handled that way.

description of https://issues.redhat.com/browse/FUSETOOLS2-405 needs to be updated then.

**Comment by lhein** [comment]
> Just to restate: This only applies to datasource properties. Environment variables are not handled that way.

I was wrong about this one. Should be filled in both cases.

**Comment by lhein** [comment]
I agree that putting in `<empty>` might confuse users. I switched to an empty string which does the trick too.

**Comment by lhein** [comment]
> ok to go with empty string.
> 
> I'm wondering if it would not be even better to support `null` or `~` for not set values but it would require also to update the "Edit property" which is not supporting it currently.

Edit Property has the same logic for setting an empty value. It defaults to empty string too, same as with using the create datasource. I think `null` is not really a nice preset as it looks like code rather than a value but I guess that's a matter of personal preference.

**Pull request merged**
