### PR TITLE
bumped several dependency versions and fixed vulnerabilities

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by apupier** [comment]
please precise in the message commit the "bumped versions", it will make it easier to read the history.
Also, at first I thought it was to bump the version of the porject, not of the dependencies

**Comment by lhein** [comment]
it was a change of only a few versions which are easily recognizable in the package.json diff.

**Comment by lhein** [comment]
It is not configured for this repo yet it seems. I will add it later.

**Comment by apupier** [comment]
it was configured: https://github.com/jboss-fuse/vscode-datavirt/pull/93

**Pull request merged**
